- hosts: all
  sudo: true
  tasks:
   - name: update cache
     apt: update_cache=yes
   - name: install base packages
     apt: name={{ item }} state=latest 
     with_items:
       - libxmu6
       - libxt6
       - libice6
       - libsm6
       - libxrandr2
       - libxfixes3
       - libxcursor1
       - libpango1.0-0
       - libhunspell-1.3-0
       - libcairo2
       - libportaudio2 
       - libjack-jackd2-0 
       - libsamplerate0
   - name: setup user
     shell: sudo usermod -G video ubuntu
   - name: setup devices
     shell: echo 'ACTION=="add", KERNEL=="vchiq", GROUP="video"' | sudo tee /etc/udev/rules.d/80-mathematica.rules
   - name: fetch libffi5
     shell: cd /tmp; wget http://ftp.us.debian.org/debian/pool/main/libf/libffi/libffi5_3.0.10-3+b1_armhf.deb
   - name: fetch Mathematica for manual installation later (need to figure out how to accept the prompts)
     shell: cd /tmp; wget http://archive.raspberrypi.org/debian/pool/main/w/wolfram-engine/wolfram-engine_10.3.1+2016012407_armhf.deb
#   - name: install mathematica
#     shell: cd /tmp; dpkg -i libffi5_3.0.10-3+b1_armhf.deb wolfram-engine_10.3.1+2016012407_armhf.deb
